version: "3"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_model_data:/root/.ollama

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "ollama serve & sleep 2 && ollama pull deepseek-r1:latest && tail -f /dev/null",
      ]

  backend:
    build: .
    command: sh -c "uvicorn src.main:app --reload --port=8000 --host=0.0.0.0"
    environment:
      - stage=development
      - OLLAMA_API_URL=http://ollama:11434
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - ollama
      - db

  db:
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_DB: nextLearning-db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  ollama_model_data:
  db_data:  
 